import logging
from hashlib import md5
from homeassistant.components.climate.const import (
    PRESET_ECO,
    SUPPORT_PRESET_MODE,
    SUPPORT_TARGET_TEMPERATURE,
    HVAC_MODE_OFF,
    HVAC_MODE_HEAT,
    PRESET_AWAY,
    PRESET_HOME,
    PRESET_SLEEP,
    PRESET_NONE,
)

HVAC_MODE_MANUAL = "manual"
HVAC_MODE_UNKNOWN = "unknown"

DEFAULT_DISCOVER_TIMEOUT = 6.0
DOMAIN = "zemismart"
_LOGGER = logging.getLogger(__name__)
UDP_KEY = md5(b"yGAdlopoPVldABfn").digest()

DEVICE_IP = "DEVICE_IP"
DEVICE_KEY = "DEVICE_KEY"
DEVICE_ID = "DEVICE_ID"
SUPPORTED_DEVICES = ["3uoeudsge0ooafig"]
SUPPORT_FLAGS = SUPPORT_TARGET_TEMPERATURE | SUPPORT_PRESET_MODE
HVAC_MODES = [HVAC_MODE_OFF, HVAC_MODE_HEAT]
PRESET_MODES = [PRESET_NONE, PRESET_ECO, PRESET_AWAY, PRESET_HOME, PRESET_SLEEP]